# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  #config.vm.box = "bento/ubuntu-16.04-i386"
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.provision :shell, path: 'bootstrap.sh', keep_color: true
  config.vm.hostname = "rails-app-box"


  config.vm.provider 'virtualbox' do |v|
    v.memory = 1024
    v.cpus = 2
  end

end
